# Site.
title: Sean Olson
locale: en_US
url: https://olson-sean-k.github.io
email: olson.sean.k@gmail.com
theme: minima

# Jekyll.
permalink: /:title/
markdown: kramdown
highlighter: rouge
kramdown:
    auto_ids: true
    footnote_nr: 1
    entity_output: as_char
    toc_levels: 1..6
    enable_coderay: false

# Theme.
minima:
    social_links:
        github: olson-sean-k
        keybase: olsonseank
        twitter: olsonseank
